### ISSUE TITLE
 getLatestBlock couldn't fetch block, Invalid params

### ISSUE THREAD

**Issue by ghost** [trustlines-network/ethstats-client#8]
The log output on one of the bootnodes is full something like the following. It has been working for some time and then stopped reporting:
```
2019-05-24T09:32:18.687488838Z [wsc] =i= The socket connection has been opened.
2019-05-24T09:32:18.687721855Z [eth]     Trying to login
2019-05-24T09:32:19.343376849Z [eth] =i= { id: [32m'bootnode2'[39m,
2019-05-24T09:32:19.343405957Z   stats:
2019-05-24T09:32:19.343411496Z    { active: [33mtrue[39m,
2019-05-24T09:32:19.343416191Z      syncing: [33mfalse[39m,
2019-05-24T09:32:19.343420458Z      mining: [33mfalse[39m,
2019-05-24T09:32:19.343424715Z      hashrate: [33m0[39m,
2019-05-24T09:32:19.343429070Z      peers: [33m19[39m,
2019-05-24T09:32:19.343433375Z      gasPrice: [32m'0'[39m,
2019-05-24T09:32:19.343437510Z      uptime: [33m100[39m } }
2019-05-24T09:32:19.344362085Z [eth] xx> getLatestBlock couldn't fetch block...
2019-05-24T09:32:19.344666361Z [eth] xx> Error: Invalid params: invalid type: null, expected a block number or 'latest', 'earliest' or 'pending'.
2019-05-24T09:32:19.344678395Z     at Object.InvalidResponse (/src/node_modules/web3/lib/web3/errors.js:35:16)
2019-05-24T09:32:19.344684069Z     at /src/node_modules/web3/lib/web3/requestmanager.js:86:36
2019-05-24T09:32:19.344691075Z     at exports.XMLHttpRequest.request.onreadystatechange (/src/node_modules/web3/lib/web3/httpprovider.js:114:13)
2019-05-24T09:32:19.344697829Z     at exports.XMLHttpRequest.dispatchEvent (/src/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
2019-05-24T09:32:19.344704931Z     at setState (/src/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
2019-05-24T09:32:19.344711486Z     at IncomingMessage.<anonymous> (/src/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
2019-05-24T09:32:19.344718563Z     at IncomingMessage.emit (events.js:194:15)
2019-05-24T09:32:19.344724797Z     at endReadableNT (_stream_readable.js:1125:12)
2019-05-24T09:32:19.344731150Z     at process._tickCallback (internal/process/next_tick.js:63:19)
2019-05-24T09:32:19.353008164Z [wsc] =✘= Socket connection has been closed
2019-05-24T09:32:19.354122173Z [wsc] =!= Reconnecting in 500 ms
2019-05-24T09:32:19.354318261Z [wsc] =!= This is attempt 1 out of 10
2019-05-24T09:32:19.855770348Z [wsc] =i= Socket reconnect attempt started
2019-05-24T09:32:20.492309767Z [wsc] =✓= Socket reconnected successfully after 1139 ms
2019-05-24T09:34:43.551356820Z [wsc] =i= The socket connection has been opened.
2019-05-24T09:34:43.554689391Z [eth]     Trying to login
2019-05-24T09:34:44.241898300Z [eth] =i= { id: [32m'bootnode2'[39m,
2019-05-24T09:34:44.241935020Z   stats:
2019-05-24T09:34:44.241940977Z    { active: [33mtrue[39m,
2019-05-24T09:34:44.241962181Z      syncing: [33mfalse[39m,
2019-05-24T09:34:44.241969058Z      mining: [33mfalse[39m,
2019-05-24T09:34:44.241974502Z      hashrate: [33m0[39m,
2019-05-24T09:34:44.241979932Z      peers: [33m19[39m,
2019-05-24T09:34:44.241985434Z      gasPrice: [32m'0'[39m,
2019-05-24T09:34:44.241990872Z      uptime: [33m100[39m } }
2019-05-24T09:34:44.243590528Z [eth] xx> getLatestBlock couldn't fetch block...
2019-05-24T09:34:44.244596103Z [eth] xx> Error: Invalid params: invalid type: null, expected a block number or 'latest', 'earliest' or 'pending'.
2019-05-24T09:34:44.244608867Z     at Object.InvalidResponse (/src/node_modules/web3/lib/web3/errors.js:35:16)
2019-05-24T09:34:44.244613289Z     at /src/node_modules/web3/lib/web3/requestmanager.js:86:36
2019-05-24T09:34:44.244617203Z     at exports.XMLHttpRequest.request.onreadystatechange (/src/node_modules/web3/lib/web3/httpprovider.js:114:13)
2019-05-24T09:34:44.244621046Z     at exports.XMLHttpRequest.dispatchEvent (/src/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
2019-05-24T09:34:44.244624887Z     at setState (/src/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
2019-05-24T09:34:44.244628531Z     at IncomingMessage.<anonymous> (/src/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
2019-05-24T09:34:44.244632627Z     at IncomingMessage.emit (events.js:194:15)
2019-05-24T09:34:44.244636157Z     at endReadableNT (_stream_readable.js:1125:12)
2019-05-24T09:34:44.244639777Z     at process._tickCallback (internal/process/next_tick.js:63:19)
2019-05-24T09:34:44.252809807Z [wsc] =✘= Socket connection has been closed
2019-05-24T09:34:44.258890630Z [wsc] =!= Reconnecting in 500 ms
2019-05-24T09:34:44.259165173Z [wsc] =!= This is attempt 1 out of 10
2019-05-24T09:34:44.760504894Z [wsc] =i= Socket reconnect attempt started
2019-05-24T09:34:45.771680238Z [wsc] =✓= Socket reconnected successfully after 1513 ms
2019-05-24T09:37:04.907419817Z [wsc] =i= The socket connection has been opened.
2019-05-24T09:37:04.908811447Z [eth]     Trying to login
2019-05-24T09:37:05.710995780Z [eth] =i= { id: [32m'bootnode2'[39m,
2019-05-24T09:37:05.711042564Z   stats:
2019-05-24T09:37:05.711051870Z    { active: [33mtrue[39m,
2019-05-24T09:37:05.711058910Z      syncing: [33mfalse[39m,
2019-05-24T09:37:05.711065684Z      mining: [33mfalse[39m,
2019-05-24T09:37:05.711071862Z      hashrate: [33m0[39m,
2019-05-24T09:37:05.711077965Z      peers: [33m19[39m,
2019-05-24T09:37:05.711083520Z      gasPrice: [32m'0'[39m,
2019-05-24T09:37:05.711089181Z      uptime: [33m100[39m } }
2019-05-24T09:37:05.712882261Z [eth] xx> getLatestBlock couldn't fetch block...
2019-05-24T09:37:05.713337720Z [eth] xx> Error: Invalid params: invalid type: null, expected a block number or 'latest', 'earliest' or 'pending'.
2019-05-24T09:37:05.713353817Z     at Object.InvalidResponse (/src/node_modules/web3/lib/web3/errors.js:35:16)
2019-05-24T09:37:05.713360622Z     at /src/node_modules/web3/lib/web3/requestmanager.js:86:36
2019-05-24T09:37:05.713366387Z     at exports.XMLHttpRequest.request.onreadystatechange (/src/node_modules/web3/lib/web3/httpprovider.js:114:13)
2019-05-24T09:37:05.713372141Z     at exports.XMLHttpRequest.dispatchEvent (/src/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
2019-05-24T09:37:05.713384328Z     at setState (/src/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
2019-05-24T09:37:05.713390261Z     at IncomingMessage.<anonymous> (/src/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
2019-05-24T09:37:05.713397307Z     at IncomingMessage.emit (events.js:194:15)
2019-05-24T09:37:05.713403147Z     at endReadableNT (_stream_readable.js:1125:12)
2019-05-24T09:37:05.713409000Z     at process._tickCallback (internal/process/next_tick.js:63:19)
2019-05-24T09:37:05.721834670Z [wsc] =✘= Socket connection has been closed
2019-05-24T09:37:05.726976359Z [wsc] =!= Reconnecting in 500 ms
2019-05-24T09:37:05.727268678Z [wsc] =!= This is attempt 1 out of 10
2019-05-24T09:37:06.228136698Z [wsc] =i= Socket reconnect attempt started
2019-05-24T09:37:06.885814107Z [wsc] =✓= Socket reconnected successfully after 1159 ms
2019-05-24T09:39:32.620143205Z [wsc] =i= The socket connection has been opened.
2019-05-24T09:39:32.620626270Z [eth]     Trying to login
2019-05-24T09:39:33.303792056Z [eth] =i= { id: [32m'bootnode2'[39m,
2019-05-24T09:39:33.303918051Z   stats:
2019-05-24T09:39:33.304097707Z    { active: [33mtrue[39m,
2019-05-24T09:39:33.304129208Z      syncing: [33mfalse[39m,
2019-05-24T09:39:33.304252157Z      mining: [33mfalse[39m,
2019-05-24T09:39:33.304276317Z      hashrate: [33m0[39m,
2019-05-24T09:39:33.304351526Z      peers: [33m20[39m,
2019-05-24T09:39:33.304379640Z      gasPrice: [32m'0'[39m,
2019-05-24T09:39:33.304482842Z      uptime: [33m100[39m } }
2019-05-24T09:39:33.305746149Z [eth] xx> getLatestBlock couldn't fetch block...
2019-05-24T09:39:33.306761748Z [eth] xx> Error: Invalid params: invalid type: null, expected a block number or 'latest', 'earliest' or 'pending'.
2019-05-24T09:39:33.306813041Z     at Object.InvalidResponse (/src/node_modules/web3/lib/web3/errors.js:35:16)
2019-05-24T09:39:33.306872624Z     at /src/node_modules/web3/lib/web3/requestmanager.js:86:36
2019-05-24T09:39:33.306906370Z     at exports.XMLHttpRequest.request.onreadystatechange (/src/node_modules/web3/lib/web3/httpprovider.js:114:13)
2019-05-24T09:39:33.306980940Z     at exports.XMLHttpRequest.dispatchEvent (/src/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
2019-05-24T09:39:33.306998319Z     at setState (/src/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
2019-05-24T09:39:33.307034607Z     at IncomingMessage.<anonymous> (/src/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
2019-05-24T09:39:33.307066800Z     at IncomingMessage.emit (events.js:194:15)
2019-05-24T09:39:33.307117647Z     at endReadableNT (_stream_readable.js:1125:12)
2019-05-24T09:39:33.307150252Z     at process._tickCallback (internal/process/next_tick.js:63:19)
2019-05-24T09:39:33.316582884Z [wsc] =✘= Socket connection has been closed
2019-05-24T09:39:33.317120126Z [wsc] =!= Reconnecting in 500 ms
2019-05-24T09:39:33.317465497Z [wsc] =!= This is attempt 1 out of 10
2019-05-24T09:39:33.818518475Z [wsc] =i= Socket reconnect attempt started
2019-05-24T09:39:34.456876665Z [wsc] =✓= Socket reconnected successfully after 1140 ms
```

**Comment by andfletcher** [comment]
Closing. Can be reopened if problem reappears.

**Comment by ghost** [comment]
The bootnodes did run into the same problem recently:
```
2019-12-15T05:43:08.723295168Z [eth] xx> getLatestBlock couldn't fetch block...
2019-12-15T05:43:08.723760248Z [eth] xx> Error: Invalid params: invalid type: null, expected a block number or 'latest', 'earliest' or 'pending'.
2019-12-15T05:43:08.723774093Z     at Object.InvalidResponse (/src/node_modules/web3/lib/web3/errors.js:35:16)
2019-12-15T05:43:08.723778446Z     at /src/node_modules/web3/lib/web3/requestmanager.js:86:36
2019-12-15T05:43:08.723804810Z     at exports.XMLHttpRequest.request.onreadystatechange (/src/node_modules/web3/lib/web3/httpprovider.js:114:13)
2019-12-15T05:43:08.723810045Z     at exports.XMLHttpRequest.dispatchEvent (/src/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
2019-12-15T05:43:08.723814132Z     at setState (/src/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
2019-12-15T05:43:08.723817020Z     at IncomingMessage.<anonymous> (/src/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
2019-12-15T05:43:08.723820535Z     at IncomingMessage.emit (events.js:203:15)
2019-12-15T05:43:08.723837737Z     at endReadableNT (_stream_readable.js:1143:12)
2019-12-15T05:43:08.723840564Z     at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by ghost** [comment]
So far, we have only seen this on the bootnodes with only 1GB of memory. Also, when I logged into one of those I got an "out of memory" error when trying to install something into a docker container.
I'm trying to give those bootnodes more memory as a first mitigation. We'll see if this helps.

**Comment by ghost** [comment]
bootnodes have been updated. I'm waiting for new findings.

**Comment by cducrest** [comment]
Closing until new findings.
